[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.8"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
